# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
#pip install pandas
#pip install scipy
#pip install seaborn
#pip install jupyter
#pip install build
#pip install setuptools
#pip install wheel

In [2]:
import pandas as pd
import scipy as sp
import seaborn as sns

Loading the Data for Q2 2026 in Data Folder, doing some very basic EDA

In [3]:
import pandas as pd
#Import the sec data, put descriptions for each thing later, but all information is in the readme in the data folder
sub = pd.read_csv("data/sub.txt", sep="\t", header=0)
num = pd.read_csv("data/num.txt", sep="\t", header=0)
pre = pd.read_csv("data/pre.txt", sep="\t", header=0)
tag = pd.read_csv("data/tag.txt", sep="\t", header=0)

#Check the shape of each dataframe, also take a look at sub to see what's in there
display(sub)
print(sub.shape)
print(num.shape)
print(pre.shape)
print(tag.shape)

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,period,fy,fp,filed,accepted,prevrpt,detail,instance,nciks,aciks
0,0000001961-26-000014,1961,GEMAXEL INC,7372.0,US,FL,MIAMI BEACH,33140,4775 COLLINS AVE,NaN,...,20250331.0,2025.0,Q1,20260605,2026-06-04 17:44:00.0,0,1,wddd10q125_htm.xml,1,NaN
1,0000001961-26-000025,1961,GEMAXEL INC,7372.0,US,FL,MIAMI BEACH,33140,4775 COLLINS AVE,NaN,...,20250630.0,2025.0,Q2,20260605,2026-06-05 16:45:00.0,0,1,wdddq22025_htm.xml,1,NaN
2,0000001961-26-000030,1961,GEMAXEL INC,7372.0,US,FL,MIAMI BEACH,33140,4775 COLLINS AVE,NaN,...,20250930.0,2025.0,Q3,20260605,2026-06-05 17:18:00.0,0,1,wdddq32025_htm.xml,1,NaN
3,0000002488-26-000076,2488,ADVANCED MICRO DEVICES INC,3674.0,US,CA,SANTA CLARA,95054,2485 AUGUSTINE DRIVE,NaN,...,20260331.0,2026.0,Q1,20260506,2026-05-05 18:06:00.0,0,1,amd-20260328_htm.xml,1,NaN
4,0000002969-26-000020,2969,"AIR PRODUCTS & CHEMICALS, INC.",2810.0,US,PA,ALLENTOWN,18106-5500,1940 AIR PRODUCTS BLVD.,NaN,...,20260331.0,2026.0,Q2,20260430,2026-04-30 11:07:00.0,0,1,apd-20260331_htm.xml,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7709,0002097163-26-000012,2097163,XANADU QUANTUM TECHNOLOGIES LTD,3571.0,NaN,NaN,TORONTO,M5G 2C8,"777 BAY STREET, SUITE 2400",NaN,...,20260331.0,2026.0,Q1,20260514,2026-05-14 16:07:00.0,0,1,xndu-20260331_htm.xml,1,NaN
7710,0002097953-26-000009,2097953,MIRA QON CORP,7374.0,US,MO,KANSAS CITY,64133,11312 E 44TH ST,NaN,...,20260228.0,2026.0,Q2,20260408,2026-04-08 11:25:00.0,0,1,mira10q02282026_htm.xml,1,NaN
7711,0002104052-26-000081,2104052,ENVIRI CORP,4953.0,US,PA,PHILADELPHIA,19103,TWO LOGAN SQUARE,"100-120 N. 18TH STREET, SUITE 1700",...,20260331.0,2026.0,Q1,20260608,2026-06-08 17:18:00.0,0,1,nvriwi-20260331_htm.xml,1,NaN
7712,0002104052-26-000118,2104052,ENVIRI CORP,4953.0,US,PA,PHILADELPHIA,19103,TWO LOGAN SQUARE,"100-120 N. 18TH STREET, SUITE 1700",...,20251231.0,NaN,NaN,20260618,2026-06-18 12:22:00.0,0,1,nvri-20260618_htm.xml,1,NaN
7713,0002104052-26-000120,2104052,ENVIRI CORP,4953.0,US,PA,PHILADELPHIA,19103,TWO LOGAN SQUARE,"100-120 N. 18TH STREET, SUITE 1700",...,20251231.0,NaN,NaN,20260618,2026-06-18 13:19:00.0,0,1,nvri-20260618_htm.xml,1,NaN

(7714, 36)
(3608711, 10)
(785490, 10)
(92731, 9)

In [4]:
#Check number of unique IDs, there are about 6 thousand for 2026 Q2
print(sub['cik'].nunique())

#See if there are any na values, sic, fy, fp have many NA values.
#Other columns with NA values are related to address
print(sub.isna().sum())

6179
adsh             0
cik              0
name             0
sic            190
countryba      582
stprba        1102
cityba           6
zipba          351
bas1             5
bas2          4178
baph             4
countryma      585
stprma        1079
cityma           7
zipma          347
mas1             6
mas2          4189
countryinc     674
stprinc       1728
ein              0
former        3307
changed       3307
afs             48
wksi             0
fye             16
form             0
period           1
fy             933
fp             951
filed            0
accepted         0
prevrpt          0
detail           0
instance         0
nciks            0
aciks         7583
dtype: int64

In [5]:
print(num.isna().sum())
#Sub and num are linked by accession number. We can see what we can access using both tables
#We can basically figure out the CIK and company name for a filing if we have the accession number
display(sub)
display(num)

adsh              0
tag               0
version           0
ddate             0
qtrs              0
uom               0
segments    1418876
coreg       3547589
value        179794
footnote    3499534
dtype: int64

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,period,fy,fp,filed,accepted,prevrpt,detail,instance,nciks,aciks
0,0000001961-26-000014,1961,GEMAXEL INC,7372.0,US,FL,MIAMI BEACH,33140,4775 COLLINS AVE,NaN,...,20250331.0,2025.0,Q1,20260605,2026-06-04 17:44:00.0,0,1,wddd10q125_htm.xml,1,NaN
1,0000001961-26-000025,1961,GEMAXEL INC,7372.0,US,FL,MIAMI BEACH,33140,4775 COLLINS AVE,NaN,...,20250630.0,2025.0,Q2,20260605,2026-06-05 16:45:00.0,0,1,wdddq22025_htm.xml,1,NaN
2,0000001961-26-000030,1961,GEMAXEL INC,7372.0,US,FL,MIAMI BEACH,33140,4775 COLLINS AVE,NaN,...,20250930.0,2025.0,Q3,20260605,2026-06-05 17:18:00.0,0,1,wdddq32025_htm.xml,1,NaN
3,0000002488-26-000076,2488,ADVANCED MICRO DEVICES INC,3674.0,US,CA,SANTA CLARA,95054,2485 AUGUSTINE DRIVE,NaN,...,20260331.0,2026.0,Q1,20260506,2026-05-05 18:06:00.0,0,1,amd-20260328_htm.xml,1,NaN
4,0000002969-26-000020,2969,"AIR PRODUCTS & CHEMICALS, INC.",2810.0,US,PA,ALLENTOWN,18106-5500,1940 AIR PRODUCTS BLVD.,NaN,...,20260331.0,2026.0,Q2,20260430,2026-04-30 11:07:00.0,0,1,apd-20260331_htm.xml,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7709,0002097163-26-000012,2097163,XANADU QUANTUM TECHNOLOGIES LTD,3571.0,NaN,NaN,TORONTO,M5G 2C8,"777 BAY STREET, SUITE 2400",NaN,...,20260331.0,2026.0,Q1,20260514,2026-05-14 16:07:00.0,0,1,xndu-20260331_htm.xml,1,NaN
7710,0002097953-26-000009,2097953,MIRA QON CORP,7374.0,US,MO,KANSAS CITY,64133,11312 E 44TH ST,NaN,...,20260228.0,2026.0,Q2,20260408,2026-04-08 11:25:00.0,0,1,mira10q02282026_htm.xml,1,NaN
7711,0002104052-26-000081,2104052,ENVIRI CORP,4953.0,US,PA,PHILADELPHIA,19103,TWO LOGAN SQUARE,"100-120 N. 18TH STREET, SUITE 1700",...,20260331.0,2026.0,Q1,20260608,2026-06-08 17:18:00.0,0,1,nvriwi-20260331_htm.xml,1,NaN
7712,0002104052-26-000118,2104052,ENVIRI CORP,4953.0,US,PA,PHILADELPHIA,19103,TWO LOGAN SQUARE,"100-120 N. 18TH STREET, SUITE 1700",...,20251231.0,NaN,NaN,20260618,2026-06-18 12:22:00.0,0,1,nvri-20260618_htm.xml,1,NaN
7713,0002104052-26-000120,2104052,ENVIRI CORP,4953.0,US,PA,PHILADELPHIA,19103,TWO LOGAN SQUARE,"100-120 N. 18TH STREET, SUITE 1700",...,20251231.0,NaN,NaN,20260618,2026-06-18 13:19:00.0,0,1,nvri-20260618_htm.xml,1,NaN

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote
0,0000001961-26-000014,AccountsPayableCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,809928.0,NaN
1,0000001961-26-000014,AccountsPayableCurrent,us-gaap/2025,20250331,0,USD,NaN,NaN,833228.0,NaN
2,0000001961-26-000014,AccruedLiabilitiesCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,1768703.0,NaN
3,0000001961-26-000014,AccruedLiabilitiesCurrent,us-gaap/2025,20250331,0,USD,NaN,NaN,1784333.0,NaN
4,0000001961-26-000014,AdditionalPaidInCapital,us-gaap/2025,20241231,0,USD,NaN,NaN,42335725.0,NaN
...,...,...,...,...,...,...,...,...,...,...
3608706,0002104052-26-000120,EmployeeBenefitPlanNoteReceivableFromParticipant,us-gaap-ebp/2026,20251231,0,USD,LegalEntity=EBP224;,EBP224,2399000.0,NaN
3608707,0002104052-26-000120,EmployeeBenefitPlanParticipantContributionRece...,us-gaap-ebp/2026,20241231,0,USD,LegalEntity=EBP224;,EBP224,0.0,NaN
3608708,0002104052-26-000120,EmployeeBenefitPlanParticipantContributionRece...,us-gaap-ebp/2026,20251231,0,USD,LegalEntity=EBP224;,EBP224,36000.0,NaN
3608709,0002104052-26-000120,EmployeeBenefitPlanReceivable,us-gaap-ebp/2026,20241231,0,USD,LegalEntity=EBP224;,EBP224,2107000.0,NaN
3608710,0002104052-26-000120,EmployeeBenefitPlanReceivable,us-gaap-ebp/2026,20251231,0,USD,LegalEntity=EBP224;,EBP224,2474000.0,NaN

In [6]:
#There are about 65 thousand unique tags, we aren't going to use all of them
unique_values = num['tag'].nunique()
#print(unique_values)

Looking For Total Assets

In [7]:
#So here, I am looking for tags that could represent total assets. I see tlabel and doc for more details
tag[tag["tag"].str.contains("assets", case=False, na=False)]

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
72,AmortizationOfIntangibleAssets,us-gaap/2024,0,0,monetary,D,D,Amortization of Intangible Assets,The aggregate expense charged against earnings...
81,Assets,us-gaap/2024,0,0,monetary,I,D,Assets,Amount of asset recognized for present right t...
82,AssetsCurrent,us-gaap/2024,0,0,monetary,I,D,"Assets, Current",Amount of asset recognized for present right t...
83,AssetsHeldForSaleNotPartOfDisposalGroupCurrent,us-gaap/2024,0,0,monetary,I,D,"Asset, Held-for-Sale, Not Part of Disposal Gro...",Amount of assets held-for-sale that are not pa...
84,AssetsHeldInTrustCurrent,us-gaap/2024,0,0,monetary,I,D,"Asset, Held-in-Trust, Current","The amount of cash, securities, or other asset..."
...,...,...,...,...,...,...,...,...,...
92651,GainLossOnSaleOfCryptoAssetsNoncashReclassified,0001214659-26-007963,1,0,monetary,D,C,GainLossOnSaleOfCryptoAssetsNoncashReclassified,NaN
92668,LossGainOnCryptoAssetSales,0001214659-26-007963,1,0,monetary,D,D,LossGainOnCryptoAssetSales,NaN
92671,NetChangeInFairValueOfCryptoAssets,0001214659-26-007963,1,0,monetary,D,C,Net change in fair value of crypto assets,NaN
92686,ProceedsFromSalesOfCryptoAssets,0001214659-26-007963,1,0,monetary,D,D,ProceedsFromSalesOfCryptoAssets,NaN
92690,PurchasesOfCryptoAssets,0001214659-26-007963,1,0,monetary,D,C,PurchasesOfCryptoAssets,NaN

In [8]:
#Here, I look for tags that are an exact match for assets in tag
tag[tag["tag"].str.strip().str.lower() == "assets"]

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
81,Assets,us-gaap/2024,0,0,monetary,I,D,Assets,Amount of asset recognized for present right t...
1398,Assets,ifrs/2024,0,0,monetary,I,D,Assets,The amount of a present economic resource cont...
1940,Assets,us-gaap/2025,0,0,monetary,I,D,Assets,Amount of asset recognized for present right t...
5764,Assets,ifrs/2025,0,0,monetary,I,D,Assets [Default Label],Amount of asset recognized for present right t...
6747,Assets,us-gaap/2026,0,0,monetary,I,D,Assets,Amount of asset recognized for present right t...

In [9]:
#Here, I look for tags that are an exact match for assets in pre. I see the plabel and tlabel are promising
pre.loc[pre['tag'] == "Assets"]

,adsh,report,line,stmt,inpth,rfile,tag,version,plabel,negating
3,0000001961-26-000014,2,5,UN,0,H,Assets,us-gaap/2025,Total assets,0
52,0000001961-26-000025,2,5,BS,0,H,Assets,us-gaap/2025,Total assets,0
103,0000001961-26-000030,2,5,BS,0,H,Assets,us-gaap/2025,Total assets,0
191,0000002488-26-000076,4,14,BS,0,H,Assets,us-gaap/2026,Total assets,0
308,0000002969-26-000020,5,28,BS,0,H,Assets,us-gaap/2025,Total Assets,0
...,...,...,...,...,...,...,...,...,...,...
784929,0002096300-26-000012,4,21,UN,0,H,Assets,us-gaap/2025,Total assets,0
785034,0002097163-26-000012,2,18,BS,0,H,Assets,us-gaap/2025,Total assets,0
785138,0002097953-26-000009,2,6,BS,0,H,Assets,us-gaap/2024,Total Assets,0
785196,0002104052-26-000081,2,19,BS,0,H,Assets,us-gaap/2025,Total assets,0
785338,0002104052-26-000081,9,28,UN,0,H,Assets,us-gaap/2025,Total assets,0

In [10]:
#Finally, I check num to see if there is any relevant information associated with the tag, like value
num.loc[num['tag'] == "Assets"]

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote
6,0000001961-26-000014,Assets,us-gaap/2025,20241231,0,USD,NaN,NaN,1.513000e+04,NaN
7,0000001961-26-000014,Assets,us-gaap/2025,20250331,0,USD,NaN,NaN,9.959000e+03,NaN
120,0000001961-26-000025,Assets,us-gaap/2025,20241231,0,USD,NaN,NaN,1.513000e+04,NaN
121,0000001961-26-000025,Assets,us-gaap/2025,20250630,0,USD,NaN,NaN,9.004000e+03,NaN
282,0000001961-26-000030,Assets,us-gaap/2025,20241231,0,USD,NaN,NaN,1.513000e+04,NaN
...,...,...,...,...,...,...,...,...,...,...
3607404,0002097953-26-000009,Assets,us-gaap/2024,20260228,0,USD,NaN,NaN,6.120300e+04,NaN
3607602,0002104052-26-000081,Assets,us-gaap/2025,20251231,0,USD,NaN,NaN,2.708671e+09,NaN
3607603,0002104052-26-000081,Assets,us-gaap/2025,20251231,0,USD,LegalEntity=NewEnviri;,NewEnviri,1.670647e+09,NaN
3607604,0002104052-26-000081,Assets,us-gaap/2025,20260331,0,USD,NaN,NaN,2.704109e+09,NaN
3607605,0002104052-26-000081,Assets,us-gaap/2025,20260331,0,USD,LegalEntity=NewEnviri;,NewEnviri,1.658385e+09,NaN

Looking For Current Assets tag Instead of Total Assets

In [11]:
#Here, because the relevant variable is two words, I try looking in doc to see if there's anything relevant, since
#looking only in tags might not be enough
tag[
    tag["doc"].str.contains("assets", case=False, na=False) & tag["doc"].str.contains("current", case=False, na=False)
]

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
247,Depreciation,us-gaap/2024,0,0,monetary,D,D,Depreciation,The amount of expense recognized in the curren...
249,DepreciationAndAmortization,us-gaap/2024,0,0,monetary,D,D,"Depreciation, Depletion and Amortization, Nonp...",The current period expense charged against ear...
251,DepreciationDepletionAndAmortization,us-gaap/2024,0,0,monetary,D,D,"Depreciation, Depletion and Amortization",The aggregate expense recognized in the curren...
505,IncreaseDecreaseInOtherCurrentAssets,us-gaap/2024,0,0,monetary,D,C,Increase (Decrease) in Other Current Assets,Amount of increase (decrease) in current asset...
506,IncreaseDecreaseInOtherCurrentAssetsAndLiabili...,us-gaap/2024,0,0,monetary,D,C,Increase (Decrease) in Other Current Assets an...,Amount of increase (decrease) in current opera...
...,...,...,...,...,...,...,...,...,...
92252,DepositsPrepaymentsAndOtherCurrentAssets,0001493152-26-031197,1,0,monetary,I,D,"Deposits, prepayments and other current assets",Deposits prepayments and other current assets.
92338,IncreaseDecreaseInPrepaidExpenseAndOtherCurren...,0001104659-26-079324,1,0,monetary,D,C,Increase (Decrease) in Prepaid Expense and Oth...,Amount of increase (decrease) in prepaid expen...
92414,IndefiniteLivedIntangibleAssetsCryptocurrencie...,0001104659-26-079335,1,0,monetary,I,D,"Indefinite Lived Intangible Assets, Cryptocurr...","Amount of assets, excluding financial assets a..."
92512,NoncashOrPartNoncashPrepaidExpensesAndOtherCur...,0001213900-26-073749,1,0,monetary,D,D,Noncash Or Part Noncash Prepaid Expenses And O...,Represent the amount of prepaid expenses and o...
92558,DepositsAndOtherCurrentAssetsNet,0001213900-26-073728,1,0,monetary,I,D,Deposits And Other Current Assets Net,Represent the amount of deposits and other cur...

In [12]:
#The above cell didn't work, and I'm having trouble finding current assets in general, so now I try looking at plabel directly
pre[pre["plabel"].str.contains("current assets", case=False, na=False)]

,adsh,report,line,stmt,inpth,rfile,tag,version,plabel,negating
2,0000001961-26-000014,2,4,UN,0,H,AssetsCurrent,us-gaap/2025,Total Current Assets,0
51,0000001961-26-000025,2,4,BS,0,H,AssetsCurrent,us-gaap/2025,Total Current Assets,0
102,0000001961-26-000030,2,4,BS,0,H,AssetsCurrent,us-gaap/2025,Total Current Assets,0
184,0000002488-26-000076,4,7,BS,0,H,PrepaidExpenseAndOtherAssetsCurrent,us-gaap/2026,Prepaid expenses and other current assets,0
185,0000002488-26-000076,4,8,BS,0,H,AssetsCurrent,us-gaap/2026,Total current assets,0
...,...,...,...,...,...,...,...,...,...,...
785136,0002097953-26-000009,2,4,BS,0,H,AssetsCurrent,us-gaap/2024,Total Current Assets,0
785187,0002104052-26-000081,2,10,BS,0,H,OtherAssetsCurrent,us-gaap/2025,Other current assets,0
785188,0002104052-26-000081,2,11,BS,0,H,AssetsCurrent,us-gaap/2025,Total current assets,0
785329,0002104052-26-000081,9,19,UN,0,H,OtherAssetsCurrent,us-gaap/2025,Other current assets,0
785330,0002104052-26-000081,9,20,UN,0,H,AssetsCurrent,us-gaap/2025,Total current assets,0

In [13]:
#After finding current assets, I then check num to see if there are values that make sense. We can see that
#in general, the current assets is a bit less than total assets, which should make sense unless I'm wrong here
num.loc[num['tag'] == "AssetsCurrent"]

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote
8,0000001961-26-000014,AssetsCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,15130.0,NaN
9,0000001961-26-000014,AssetsCurrent,us-gaap/2025,20250331,0,USD,NaN,NaN,9959.0,NaN
122,0000001961-26-000025,AssetsCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,15130.0,NaN
123,0000001961-26-000025,AssetsCurrent,us-gaap/2025,20250630,0,USD,NaN,NaN,9004.0,NaN
284,0000001961-26-000030,AssetsCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,15130.0,NaN
...,...,...,...,...,...,...,...,...,...,...
3607406,0002097953-26-000009,AssetsCurrent,us-gaap/2024,20260228,0,USD,NaN,NaN,314.0,NaN
3607606,0002104052-26-000081,AssetsCurrent,us-gaap/2025,20251231,0,USD,NaN,NaN,720681000.0,NaN
3607607,0002104052-26-000081,AssetsCurrent,us-gaap/2025,20251231,0,USD,LegalEntity=NewEnviri;,NewEnviri,695749000.0,NaN
3607608,0002104052-26-000081,AssetsCurrent,us-gaap/2025,20260331,0,USD,NaN,NaN,722110000.0,NaN
3607609,0002104052-26-000081,AssetsCurrent,us-gaap/2025,20260331,0,USD,LegalEntity=NewEnviri;,NewEnviri,705289000.0,NaN

In [14]:
#I also check tag as well to make sure the tlabel is right
tag.loc[tag['tag'] == "AssetsCurrent"]

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
82,AssetsCurrent,us-gaap/2024,0,0,monetary,I,D,"Assets, Current",Amount of asset recognized for present right t...
1941,AssetsCurrent,us-gaap/2025,0,0,monetary,I,D,"Assets, Current",Amount of asset recognized for present right t...
6875,AssetsCurrent,us-gaap/2026,0,0,monetary,I,D,"Assets, Current",Amount of asset recognized for present right t...

Checking Tag For Current Liabilities

In [15]:
#So now I've done this a few times, I decide to look directly at plabel and tlabel to figure out what tags I'm looking for
pre[pre["plabel"].str.contains("total current liabilities", case=False, na=False)]

,adsh,report,line,stmt,inpth,rfile,tag,version,plabel,negating
9,0000001961-26-000014,2,11,UN,0,H,LiabilitiesCurrent,us-gaap/2025,Total Current Liabilities,0
58,0000001961-26-000025,2,11,BS,0,H,LiabilitiesCurrent,us-gaap/2025,Total Current Liabilities,0
109,0000001961-26-000030,2,11,BS,0,H,LiabilitiesCurrent,us-gaap/2025,Total Current Liabilities,0
196,0000002488-26-000076,4,21,BS,0,H,LiabilitiesCurrent,us-gaap/2026,Total current liabilities,0
314,0000002969-26-000020,5,36,BS,0,H,LiabilitiesCurrent,us-gaap/2025,Total Current Liabilities,0
...,...,...,...,...,...,...,...,...,...,...
784935,0002096300-26-000012,4,29,UN,0,H,LiabilitiesCurrent,us-gaap/2025,Total current liabilities,0
785042,0002097163-26-000012,2,28,BS,0,H,LiabilitiesCurrent,us-gaap/2025,Total current liabilities,0
785141,0002097953-26-000009,2,10,BS,0,H,LiabilitiesCurrent,us-gaap/2024,Total Current Liabilities,0
785207,0002104052-26-000081,2,33,BS,0,H,LiabilitiesCurrent,us-gaap/2025,Total current liabilities,0
785349,0002104052-26-000081,9,42,UN,0,H,LiabilitiesCurrent,us-gaap/2025,Total current liabilities,0

In [16]:
#So here I check the tlabel to see if liabilities current is correct, but the tlabel isn't consistent.
#I didn't see anything better during my investigation, but this could just be a limitation of the data really,
# I decided to go ahead with LiabilitiesCurrent because of how the plabels were so consistent.
tag[tag["tag"].str.contains("LiabilitiesCurrent", case=False, na=False)]

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
2,AccountsPayableAndAccruedLiabilitiesCurrent,us-gaap/2024,0,0,monetary,I,C,"Accounts Payable and Accrued Liabilities, Current",Sum of the carrying values as of the balance s...
3,AccountsPayableAndAccruedLiabilitiesCurrentAnd...,us-gaap/2024,0,0,monetary,I,C,Accounts Payable and Accrued Liabilities,Sum of the carrying values as of the balance s...
5,AccountsPayableAndOtherAccruedLiabilitiesCurrent,us-gaap/2024,0,0,monetary,I,C,Accounts Payable and Other Accrued Liabilities...,Amount of liabilities incurred to vendors for ...
24,AccruedLiabilitiesCurrent,us-gaap/2024,0,0,monetary,I,C,"Accrued Liabilities, Current",Carrying value as of the balance sheet date of...
25,AccruedLiabilitiesCurrentAndNoncurrent,us-gaap/2024,0,0,monetary,I,C,Accrued Liabilities,Carrying value as of the balance sheet date of...
...,...,...,...,...,...,...,...,...,...
90830,LiquidationAccountsPayableAndAccruedLiabilitie...,0001493152-26-030232,1,0,monetary,I,C,LiquidationAccountsPayableAndAccruedLiabilitie...,Liquidation accounts payable and accrued liabi...
90950,AccruedLiabilitiesCurrent1,0001683168-26-005121,1,0,monetary,I,C,Accrued liabilities,NaN
91360,EarnoutLiabilitiesCurrent,0000353184-26-000054,1,0,monetary,I,C,"Earnout Liabilities, Current","Earnout Liabilities, Current"
91376,AccruedAndOtherLiabilitiesCurrent,0001493152-26-030438,1,0,monetary,I,C,Accrued and other liabilities,Carrying value as of the balance sheet date of...
91681,LeaseLiabilitiesCurrentPortion,0001171843-26-004360,1,0,monetary,I,C,Lease liabilities - current portion,NaN

In [20]:
#I go through num to see if there is a corresponding value
num.loc[num['tag'] == "LiabilitiesCurrent"]

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote
56,0000001961-26-000014,LiabilitiesCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,3668675.0,NaN
57,0000001961-26-000014,LiabilitiesCurrent,us-gaap/2025,20250331,0,USD,NaN,NaN,3780105.0,NaN
180,0000001961-26-000025,LiabilitiesCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,3668675.0,NaN
181,0000001961-26-000025,LiabilitiesCurrent,us-gaap/2025,20250630,0,USD,NaN,NaN,3918217.0,NaN
344,0000001961-26-000030,LiabilitiesCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,3668675.0,NaN
...,...,...,...,...,...,...,...,...,...,...
3607460,0002097953-26-000009,LiabilitiesCurrent,us-gaap/2024,20260228,0,USD,NaN,NaN,88263.0,NaN
3607917,0002104052-26-000081,LiabilitiesCurrent,us-gaap/2025,20251231,0,USD,NaN,NaN,634024000.0,NaN
3607918,0002104052-26-000081,LiabilitiesCurrent,us-gaap/2025,20251231,0,USD,LegalEntity=NewEnviri;,NewEnviri,456451000.0,NaN
3607919,0002104052-26-000081,LiabilitiesCurrent,us-gaap/2025,20260331,0,USD,NaN,NaN,640692000.0,NaN
3607920,0002104052-26-000081,LiabilitiesCurrent,us-gaap/2025,20260331,0,USD,LegalEntity=NewEnviri;,NewEnviri,458141000.0,NaN

Getting the Tag for Total Liabilities

In [21]:
#I decided since I have the time to do total liabilties as well so that there are four tags left, two for each person
#I see Liabilities by itself might mean something
pre[
    pre["plabel"].str.contains("total", case=False, na=False) & pre["plabel"].str.contains("liabilities", case=False, na=False)
]

,adsh,report,line,stmt,inpth,rfile,tag,version,plabel,negating
9,0000001961-26-000014,2,11,UN,0,H,LiabilitiesCurrent,us-gaap/2025,Total Current Liabilities,0
10,0000001961-26-000014,2,12,UN,0,H,Liabilities,us-gaap/2025,Total Liabilities,0
16,0000001961-26-000014,2,18,UN,0,H,LiabilitiesAndStockholdersEquity,us-gaap/2025,Total Liabilities and stockholders' deficit,0
58,0000001961-26-000025,2,11,BS,0,H,LiabilitiesCurrent,us-gaap/2025,Total Current Liabilities,0
59,0000001961-26-000025,2,12,BS,0,H,Liabilities,us-gaap/2025,Total Liabilities,0
...,...,...,...,...,...,...,...,...,...,...
785214,0002104052-26-000081,2,40,BS,0,H,Liabilities,us-gaap/2025,Total liabilities,0
785224,0002104052-26-000081,2,51,BS,0,H,LiabilitiesAndStockholdersEquity,us-gaap/2025,Total liabilities and equity,0
785349,0002104052-26-000081,9,42,UN,0,H,LiabilitiesCurrent,us-gaap/2025,Total current liabilities,0
785356,0002104052-26-000081,9,49,UN,0,H,Liabilities,us-gaap/2025,Total liabilities,0
785362,0002104052-26-000081,9,56,UN,0,H,LiabilitiesAndStockholdersEquity,us-gaap/2025,Total liabilities and equity,0

In [23]:
#I check the tlabel to see if there is anything,
#even if the tlabel is just liabilities there isn't anything
#that would indicate we shouldn't use liabilities as the tag
#for total liabilities
tag.loc[tag["tag"] == "Liabilities"]

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
642,Liabilities,us-gaap/2024,0,0,monetary,I,C,Liabilities,Amount of liability recognized for present obl...
1668,Liabilities,ifrs/2024,0,0,monetary,I,C,Liabilities,The amount of a present obligation of the enti...
2012,Liabilities,us-gaap/2025,0,0,monetary,I,C,Liabilities,Amount of liability recognized for present obl...
5804,Liabilities,ifrs/2025,0,0,monetary,I,C,Liabilities [Default Label],Amount of liability recognized for present obl...
6800,Liabilities,us-gaap/2026,0,0,monetary,I,C,Liabilities [Default Label],Amount of liability recognized for present obl...

In [24]:
#I check liabilities in num to see if it makes sense,
#considering how large the values are, it would be strange if it
#didn't represent total liabilities
num.loc[num['tag'] == "Liabilities"]

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote
52,0000001961-26-000014,Liabilities,us-gaap/2025,20241231,0,USD,NaN,NaN,3.668675e+06,NaN
53,0000001961-26-000014,Liabilities,us-gaap/2025,20250331,0,USD,NaN,NaN,3.780105e+06,NaN
176,0000001961-26-000025,Liabilities,us-gaap/2025,20241231,0,USD,NaN,NaN,3.668675e+06,NaN
177,0000001961-26-000025,Liabilities,us-gaap/2025,20250630,0,USD,NaN,NaN,3.918217e+06,NaN
340,0000001961-26-000030,Liabilities,us-gaap/2025,20241231,0,USD,NaN,NaN,3.668675e+06,NaN
...,...,...,...,...,...,...,...,...,...,...
3607456,0002097953-26-000009,Liabilities,us-gaap/2024,20260228,0,USD,NaN,NaN,8.826300e+04,NaN
3607909,0002104052-26-000081,Liabilities,us-gaap/2025,20251231,0,USD,NaN,NaN,2.413084e+09,NaN
3607910,0002104052-26-000081,Liabilities,us-gaap/2025,20251231,0,USD,LegalEntity=NewEnviri;,NewEnviri,2.239008e+09,NaN
3607911,0002104052-26-000081,Liabilities,us-gaap/2025,20260331,0,USD,NaN,NaN,2.429198e+09,NaN
3607912,0002104052-26-000081,Liabilities,us-gaap/2025,20260331,0,USD,LegalEntity=NewEnviri;,NewEnviri,2.274946e+09,NaN

For the next section, the goal is to get tags for two of the remaining variables per person, and then focus on figuring out how to standardize the four dataset into a dataframe we can use for the model. It should be something like, for each row, a CIK value, the date, and the various variable values. We can have it ordered where a group of data points can represent the same CIK id across different dates based on the number of filings they made, almost like an order by. Once the two tags are done, standardizing the data should be the goal. Hopefully, that should be done by the end of this week. I will work on getting a bankruptcy indication or label so that we can move on directly to XGBoost.

Getting the Tag For Revenue

Getting the Tag for Net Income or Total Income, whichever is best

Getting the tag for Operating Income

Getting the tag for Operating Cash Flow

Making a Standardized Dataset From the Four Dataframes and Tags We Found